export interface ReklameData {
  displayFieldName: string;
  fieldAliases: {
    [fieldName: string]: string,
  };
  geometryType: string;
  spatialReference: {
    wkid: number,
    latestWkid: number,
  };
  fields: {
    name: string,
    type: string,
    alias: string,
    length?: number,
  }[];
  features: {
    attributes: {
      ALMT_PMLK_IJIN: string | null,
      ALMT_PMLK_IJINI_KTN: string | null,
      BERADA_DI: string | null,
      BERBAHAYA: string | null,
      CAT_BERBAHAYA: string | null,
      CAT_KONDISI: string | null,
      CAT_PENINDAKAN: string | null,
      CREATED_AT: string,
      CREATED_BY: string,
      CREATED_BY_ID: number,
      DIPASANG_PADA: string,
      EMAIL_PMLK_IJIN: string | null,
      EMAIL_PMLK_IJIN_KTN: string | null,
      GROUP_BY: string,
      GROUP_BY_ID: number,
      ID_REF: string | null,
      INFO_PNYLNGGRA: string,
      IS_DELETE: number,
      JENIS: string,
      JENIS_TINDAKAN: string | null,
      KAWASAN: string,
      KD_BERADA_DI: number,
      KD_BERBAHAYA: string | null,
      KD_DIPASANG_PADA: number,
      KD_JENIS: number,
      KD_JENIS_TINDAKAN: number,
      KD_KAWASAN: number,
      KD_KEC: string,
      KD_KEC_PMLK_IJIN: string,
      KD_KEC_PMLK_IJIN_KTN: string,
      KD_KEL: string,
      KD_KEL_PMLK_IJIN: string,
      KD_KEL_PMLK_IJIN_KTN: string,
      KD_KONDISI: number,
      KD_LINGKUP: number,
      KD_MUKA: number,
      KD_PELETAKAN: number,
      KD_POSISI: number,
      KD_STATUS: number,
      KD_STATUS_IJIN: number,
      KD_STATUS_PAJAK: number,
      KD_STRUKTUR: number,
      KD_WIL: string,
      KD_WIL_PMLK_IJIN: string,
      KD_WIL_PMLK_IJIN_KTN: string,
      KEC: string,
      KEC_PMLK_IJIN: string | null,
      KEC_PMLK_IJIN_KTN: string,
      KEL: string,
      KEL_PMLK_IJIN: string | null,
      KEL_PMLK_IJIN_KTN: string,
      KET_LAINNYA: string,
      KODE: string,
      KOMENTAR: string | null,
      KONDISI: string,
      KONTEN: string,
      LEBAR: string,
      LINGKUP: string,
      LOKASI: string,
      LON_UNIF: string | null,
      LUM_JALAN: string | null,
      MS_HBS_BRLKU: string | null,
      MS_IJIN: string | null,
      MUKA: string | null,
      NIK_PMLK_IJIN: string | null,
      NIK_PMLK_IJIN_KTN: string,
      NILAI_PAJAK: string | null,
      NM_PMLK_IJIN: string | null,
      NM_PMLK_IJIN_KTN: string,
      NM_PNYLNGGRA: string,
      NO_DOCUMENT: string | null,
      NO_IMB: string | null,
      NO_IPR: string | null,
      NO_PPR: string,
      NO_TINDAKAN: string | null,
      NO_TLB: string | null,
      NPWP_PMLK_IJIN: string | null,
      NPWP_PMLK_IJIN_KTN: string | null,
      OBJECTID: number,
      OBJECTID_REL: string | null,
      OVL_UNIF: string | null,
      PANJANG: string,
      PELETAKAN: string | null,
      PENENG: string,
      POSISI: string,
      REKLAME_ID: number,
      REKLAME_ID_BPRD: string | null,
      REKLAME_ID_PTSP: string | null,
      REKLAME_ID_SATPOLPP: string | null,
      REL_OBJECTID: string | null,
      STATUS: string | null,
      STATUS_IJIN: string | null,
      STATUS_PAJAK: string | null,
      STRUKTUR: string,
      TELP_PMLK_IJIN: string | null,
      TELP_PNYLNGGRA: string | null,
      TGL_AKHR_PMSNGN: string | null,
      TGL_IJIN: string | null,
      TGL_PASANG: string | null,
      TGL_SURVEY: string,
      TGL_TINDAKAN: string | null,
      THRSLD_INC: string | null,
      TINGGI: string,
      UPDATED_AT: string | null,
      UPDATED_BY: string | null,
      UPDATED_BY_ID: string | null,
      WIL: string,
      WIL_PMLK_IJIN: string | null,
      WIL_PMLK_IJIN_KTN: string,
      X: number,
      Y: number,
    },
    geometry: {
      x: number,
      y: number,
    },
  }[];
}
