import {
  AttachmentInterface,
  ResponseAtributInterface,
  BaseAtributInterface,
  ReklameArcgisInterface,
} from './interface';

export const AttachmentData: AttachmentInterface = {
  filename: '',
  url: '',
};

export const ResponseAtributData: ResponseAtributInterface = {
  ALMT_PMLK_IJIN: null,
  ALMT_PMLK_IJINI_KTN: null,
  ATTACHMENT: [AttachmentData], 
  BERADA_DI: null,
  BERBAHAYA: null,
  CAT_BERBAHAYA: null,
  CAT_KONDISI: null,
  CREATED_AT: '',
  CREATED_BY: '',
  CREATED_BY_ID: 4,
  DIPASANG_PADA: null,
  EMAIL_PMLK_IJIN: null,
  EMAIL_PMLK_IJIN_KTN: null,
  INFO_PNYLNGGRA: null,
  JENIS: '',
  JENIS_TINDAKAN: null,
  KAWASAN: '',
  KD_BERADA_DI: 0,
  KD_BERBAHAYA: null,
  KD_DIPASANG_PADA: 0,
  KD_JENIS: 3,
  KD_JENIS_TINDAKAN: 0,
  KD_KAWASAN: 3,
  KD_KEC: '',
  KD_KEC_PMLK_IJIN: '',
  KD_KEC_PMLK_IJIN_KTN: '',
  KD_KEL: '',
  KD_KEL_PMLK_IJIN: '',
  KD_KEL_PMLK_IJIN_KTN: '',
  KD_KONDISI: 0,
  KD_LINGKUP: 0,
  KD_MUKA: 0,
  KD_PELETAKAN: 0,
  KD_POSISI: 4,
  KD_STATUS: 0,
  KD_STATUS_IJIN: 0,
  KD_STATUS_PAJAK: 0,
  KD_STRUKTUR: 1,
  KD_WIL: '',
  KD_WIL_PMLK_IJIN: '',
  KD_WIL_PMLK_IJIN_KTN: '',
  KEC: '',
  KEC_PMLK_IJIN: null,
  KEC_PMLK_IJIN_KTN: null,
  KEL: '',
  KEL_PMLK_IJIN: null,
  KEL_PMLK_IJIN_KTN: null,
  KET_LAINNYA: '',
  KODE: '',
  KOMENTAR: null,
  KONDISI: '',
  KONTEN: '',
  LEBAR: '',
  LINGKUP: '',
  LOKASI: '',
  MS_HBS_BRLKU: null,
  MS_IJIN: null,
  MUKA: null,
  NIK_PMLK_IJIN: null,
  NIK_PMLK_IJIN_KTN: null,
  NILAI_PAJAK: null,
  NM_PMLK_IJIN: null,
  NM_PMLK_IJIN_KTN: null,
  NM_PNYLNGGRA: null,
  NO_IMB: null,
  NO_IPR: null,
  NO_PPR: null,
  NO_TINDAKAN: null,
  NO_TLB: null,
  NPWP_PMLK_IJIN: null,
  NPWP_PMLK_IJIN_KTN: null,
  OBJECTID: 11553,
  PANJANG: '',
  PELETAKAN: null,
  PENENG: null,
  POSISI: '',
  REKLAME_ID: 1143,
  REL_OBJECTID: '',
  STATUS: null,
  STATUS_IJIN: null,
  STATUS_PAJAK: null,
  STRUKTUR: '',
  TELP_PMLK_IJIN: null,
  TELP_PNYLNGGRA: null,
  TGL_AKHR_PMSNGN: null,
  TGL_IJIN: null,
  TGL_PASANG: null,
  TGL_SURVEY: null,
  TGL_TINDAKAN: null,
  TINGGI: '',
  UPDATED_AT: null,
  UPDATED_BY: null,
  UPDATED_BY_ID: null,
  WIL: '',
  WIL_PMLK_IJIN: null,
  WIL_PMLK_IJIN_KTN: null,
  X: 106.75051833,
  Y: -6.23672,
};

export const baseAtributData: BaseAtributInterface = {
  ALMT_PMLK_IJIN: null,
  ALMT_PMLK_IJINI_KTN: null,
  BERADA_DI: null,
  BERBAHAYA: null,
  CAT_BERBAHAYA: null,
  CAT_KONDISI: null,
  CAT_PENINDAKAN: null,
  CREATED_AT: null,
  CREATED_BY: null,
  CREATED_BY_ID: 4,
  DIPASANG_PADA: null,
  EMAIL_PMLK_IJIN: null,
  EMAIL_PMLK_IJIN_KTN: null,
  GROUP_BY: null,
  GROUP_BY_ID: 4,
  ID_REF: null,
  INFO_PNYLNGGRA: null,
  IS_DELETE: 0,
  JENIS: null,
  JENIS_TINDAKAN: null,
  KAWASAN: null,
  KD_BERADA_DI: 0,
  KD_BERBAHAYA: null,
  KD_DIPASANG_PADA: 1,
  KD_JENIS: 1,
  KD_JENIS_TINDAKAN: 0,
  KD_KAWASAN: 1,
  KD_KEC: null,
  KD_KEC_PMLK_IJIN: null,
  KD_KEC_PMLK_IJIN_KTN: null,
  KD_KEL: null,
  KD_KEL_PMLK_IJIN: null,
  KD_KEL_PMLK_IJIN_KTN: null,
  KD_KONDISI: 0,
  KD_LINGKUP: 0,
  KD_MUKA: 0,
  KD_PELETAKAN: 0,
  KD_POSISI: 3,
  KD_STATUS: 0,
  KD_STATUS_IJIN: 0,
  KD_STATUS_PAJAK: 0,
  KD_STRUKTUR: 2,
  KD_WIL: null,
  KD_WIL_PMLK_IJIN: null,
  KD_WIL_PMLK_IJIN_KTN: null,
  KEC: null,
  KEC_PMLK_IJIN: null,
  KEC_PMLK_IJIN_KTN: null,
  KEL: null,
  KEL_PMLK_IJIN: null,
  KEL_PMLK_IJIN_KTN: null,
  KET_LAINNYA: null,
  KODE: null,
  KOMENTAR: null,
  KONDISI: null,
  KONTEN: null,
  LEBAR: null,
  LINGKUP: null,
  LOKASI: null,
  LON_UNIF: null,
  LUM_JALAN: null,
  MS_HBS_BRLKU: null,
  MS_IJIN: null,
  MUKA: null,
  NIK_PMLK_IJIN: null,
  NIK_PMLK_IJIN_KTN: null,
  NILAI_PAJAK: null,
  NM_PMLK_IJIN: null,
  NM_PMLK_IJIN_KTN: null,
  NM_PNYLNGGRA: null,
  NO_DOCUMENT: null,
  NO_IMB: null,
  NO_IPR: null,
  NO_PPR: null,
  NO_TINDAKAN: null,
  NO_TLB: null,
  NPWP_PMLK_IJIN: null,
  NPWP_PMLK_IJIN_KTN: null,
  OBJECTID: 23584,
  OBJECTID_REL: null,
  OVL_UNIF: null,
  PANJANG: null,
  PELETAKAN: null,
  PENENG: null,
  POSISI: null,
  REKLAME_ID: 41,
  REKLAME_ID_BPRD: null,
  REKLAME_ID_PTSP: null,
  REKLAME_ID_SATPOLPP: null,
  REL_OBJECTID: null,
  STATUS: null,
  STATUS_IJIN: null,
  STATUS_PAJAK: null,
  STRUKTUR: null,
  TELP_PMLK_IJIN: null,
  TELP_PNYLNGGRA: null,
  TGL_AKHR_PMSNGN: null,
  TGL_IJIN: null,
  TGL_PASANG: null,
  TGL_SURVEY: null,
  TGL_TINDAKAN: null,
  THRSLD_INC: null,
  TINGGI: null,
  UPDATED_AT: null,
  UPDATED_BY: null,
  UPDATED_BY_ID: null,
  WIL: null,
  WIL_PMLK_IJIN: null,
  WIL_PMLK_IJIN_KTN: null,
  X: 106.7927189,
  Y: -6.17554561,
};

export const ReklameArcgisData: ReklameArcgisInterface = {
  displayFieldName: null,
  fieldAliases: {
    field1: null,
    field2: null,
    // Add aliases for other fields as needed
  },
  geometryType: null,
  spatialReference: {
    wkid: 4326,
    latestWkid: 4326,
  },
  fields: [
    {
      name: null,
      type: null,
      alias: null,
    },
    {
      name: null,
      type: null,
      alias: null,
    },
  ],
  features: [
    {
      attributes: baseAtributData,
      geometry: {
        x: 123.456,
        y: 789.012,
      },
    },
  ],
};
