import { ReklameData } from './interface';

export const sampleReklameData: ReklameData = {
  displayFieldName: 'Sample Display Field',
  fieldAliases: {
    field1: 'Field 1 Alias',
    field2: 'Field 2 Alias',
    // Add aliases for other fields as needed
  },
  geometryType: 'Point',
  spatialReference: {
    wkid: 4326,
    latestWkid: 4326,
  },
  fields: [
    {
      name: 'field1',
      type: 'string',
      alias: 'Field 1',
    },
    {
      name: 'field2',
      type: 'number',
      alias: 'Field 2',
    },
  ],
  features: [
    {
      attributes: {
        ALMT_PMLK_IJIN: null,
        ALMT_PMLK_IJINI_KTN: null,
        BERADA_DI: null,
        BERBAHAYA: null,
        CAT_BERBAHAYA: null,
        CAT_KONDISI: null,
        CAT_PENINDAKAN: null,
        CREATED_AT: '2018-07-31 00:00:00',
        CREATED_BY: 'PTSP 1',
        CREATED_BY_ID: 4,
        DIPASANG_PADA: 'PROTOKOL A',
        EMAIL_PMLK_IJIN: null,
        EMAIL_PMLK_IJIN_KTN: null,
        GROUP_BY: 'DCKTRP',
        GROUP_BY_ID: 4,
        ID_REF: null,
        INFO_PNYLNGGRA: '1',
        IS_DELETE: 0,
        JENIS: 'Papan/Billboard',
        JENIS_TINDAKAN: null,
        KAWASAN: 'Kawasan Kendali Ketat',
        KD_BERADA_DI: 0,
        KD_BERBAHAYA: null,
        KD_DIPASANG_PADA: 1,
        KD_JENIS: 1,
        KD_JENIS_TINDAKAN: 0,
        KD_KAWASAN: 1,
        KD_KEC: '732',
        KD_KEC_PMLK_IJIN: '0',
        KD_KEC_PMLK_IJIN_KTN: '732',
        KD_KEL: '1003732',
        KD_KEL_PMLK_IJIN: '0',
        KD_KEL_PMLK_IJIN_KTN: '1003732',
        KD_KONDISI: 0,
        KD_LINGKUP: 0,
        KD_MUKA: 0,
        KD_PELETAKAN: 0,
        KD_POSISI: 3,
        KD_STATUS: 0,
        KD_STATUS_IJIN: 0,
        KD_STATUS_PAJAK: 0,
        KD_STRUKTUR: 2,
        KD_WIL: '73',
        KD_WIL_PMLK_IJIN: '0',
        KD_WIL_PMLK_IJIN_KTN: '73',
        KEC: 'GROGOL PETAMBURAN',
        KEC_PMLK_IJIN: null,
        KEC_PMLK_IJIN_KTN: 'GROGOL PETAMBURAN',
        KEL: 'TOMANG',
        KEL_PMLK_IJIN: null,
        KEL_PMLK_IJIN_KTN: 'TOMANG',
        KET_LAINNYA: '-. DIBAWAH TOL KEMUNGKINAN ADA IZIN',
        KODE: '1473000001',
        KOMENTAR: null,
        KONDISI: 'Kondisi terawat',
        KONTEN: 'Kosong',
        LEBAR: '2',
        LINGKUP: 'DINAS',
        LOKASI: 'Jl Letjen S Parman KM 13+800BY (depan Telkom)',
        LON_UNIF: null,
        LUM_JALAN: null,
        MS_HBS_BRLKU: null,
        MS_IJIN: null,
        MUKA: null,
        NIK_PMLK_IJIN: null,
        NIK_PMLK_IJIN_KTN: '3674031707560011',
        NILAI_PAJAK: null,
        NM_PMLK_IJIN: null,
        NM_PMLK_IJIN_KTN: 'PT Rainbow Asia Posters',
        NM_PNYLNGGRA: 'Rainbow',
        NO_DOCUMENT: null,
        NO_IMB: null,
        NO_IPR: null,
        NO_PPR: '2411807050562',
        NO_TINDAKAN: null,
        NO_TLB: null,
        NPWP_PMLK_IJIN: null,
        NPWP_PMLK_IJIN_KTN: null,
        OBJECTID: 23584,
        OBJECTID_REL: null,
        OVL_UNIF: null,
        PANJANG: '0',
        PELETAKAN: null,
        PENENG: '2',
        POSISI: 'Aset Jasa Marga',
        REKLAME_ID: 41,
        REKLAME_ID_BPRD: null,
        REKLAME_ID_PTSP: null,
        REKLAME_ID_SATPOLPP: null,
        REL_OBJECTID: '17',
        STATUS: null,
        STATUS_IJIN: null,
        STATUS_PAJAK: null,
        STRUKTUR: 'JPO',
        TELP_PMLK_IJIN: null,
        TELP_PNYLNGGRA: null,
        TGL_AKHR_PMSNGN: null,
        TGL_IJIN: null,
        TGL_PASANG: null,
        TGL_SURVEY: '2018-11-06 17:00:00',
        TGL_TINDAKAN: null,
        THRSLD_INC: null,
        TINGGI: '0',
        UPDATED_AT: null,
        UPDATED_BY: null,
        UPDATED_BY_ID: null,
        WIL: 'JAKARTA BARAT',
        WIL_PMLK_IJIN: null,
        WIL_PMLK_IJIN_KTN: 'JAKARTA BARAT',
        X: 106.7927189,
        Y: -6.17554561,
      },
      geometry: {
        x: 123.456,
        y: 789.012,
      },
    },
    // Add more features as needed
  ],
};
